package constants

type CuisineChoices int

const (
	SouthIndian CuisineChoices = iota
	NorthIndian
	Chinese

	USER_CUISINES_LIST  = "USER_CUISINES_LIST"
	USER_COST_TYPE_LIST = "USER_COST_TYPE_LIST"

	CUISINE_TYPE_COUNT        = 3
	COST_TYPE_COUNT           = 3
	NEW_RESTAURANT_HOUR_LIMIT = 48
	TOTAL_RECOMMENDATION      = 100

	RECOMMENDED_RESTAURANTS_KEY = "RECOMMENDED_RESTAURANTS"
	NEW_RESTAURANTS_KEY         = "NEW_RESTAURANTS"
	CUISINE_RESTAURANT_KEY      = "CUISINE_%v_RESTAURANTS"
	COST_RESTAURANT_KEY         = "COST_%d_RESTAURANTS"
	RATING_RESTAURANT_KEY       = "RATING_%s_RESTAURANTS"
	RESULT_RECOMMENDATION_KEY   = "RESULT_RECOM_KEY"
	ALL_RECOMMENDATION_KEY      = "ALL_RESTAURANTS"
	RESTAURANT_INFO             = "RESTAURANT_INFO_%v"
)
